# Autogenerated wrapper script for libdmg_hfsplus_jll for x86_64-unknown-freebsd
export dmg, hdutil, hfsplus

using LZFSE_jll
using Zlib_jll
using Bzip2_jll
using XZ_jll
using OpenSSL_jll
JLLWrappers.@generate_wrapper_header("libdmg_hfsplus")
JLLWrappers.@declare_executable_product(dmg)
JLLWrappers.@declare_executable_product(hdutil)
JLLWrappers.@declare_executable_product(hfsplus)
function __init__()
    JLLWrappers.@generate_init_header(LZFSE_jll, Zlib_jll, Bzip2_jll, XZ_jll, OpenSSL_jll)
    JLLWrappers.@init_executable_product(
        dmg,
        "bin/dmg",
    )

    JLLWrappers.@init_executable_product(
        hdutil,
        "bin/hdutil",
    )

    JLLWrappers.@init_executable_product(
        hfsplus,
        "bin/hfsplus",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
